### ISSUE TITLE
Add another Nord Firefox theme

### ISSUE THREAD

**Issue by dragonejt** [Aceto1/awesome-nord#1]
Hello,
Could you please add my Nord Theme (https://addons.mozilla.org/en-US/firefox/addon/nord-firefox/) to the GitHub Repository as well? Also, for browser themes, could you maybe add theme images?

![nord-firefox](https://user-images.githubusercontent.com/23247706/105216949-17acd200-5b08-11eb-877d-586b770704b6.png)

If needed, I can fork and then submit at PR that adds this.

Thank you!

**Comment by Aceto1** [comment]
Hey, thanks I'll look into it!

I thought about adding images but I have the feeling that once a few more ports get added it might become bloated. I'll think about it though.

**Comment by dragonejt** [comment]
Oh yeah, I hadn't considered that. Yeah probably continuing with just the links for now might be the best option.

**Comment by Aceto1** [comment]
I thought about adding a website that contains this list and images for every theme (if there are any). That would be a viable place for them. I don't have that much time right now so it might take a few weeks before I get to it.

**Comment by Aceto1** [comment]
Added!
